export const questions = [
  {
    id: "q1",
    question: "What is the main purpose of Innovation Festival?",
    options: [
      "To see who the incoming Garage@EEE President is",
      "To celebrate Garage@EEE's milestones and showcase Garage@EEE projects",
      "For members to enjoy free food and merch",
      "To hold a farewell party for Garage members",
    ],
    correctIndex: 1,
    durationSeconds: 20,
  },
  {
    id: "q2",
    question: "Where is Garage located?",
    options: ["S1-B4c-26", "S1-B3b-27", "S1-B3c-26", "S1-B4b-26"],
    correctIndex: 2,
    durationSeconds: 20,
  },
  {
    id: "q3",
    question: "How many portfolios are there in Garage?",
    options: ["5", "6", "7", "8"],
    correctIndex: 1,
    durationSeconds: 20,
  },
  {
    id: "q4",
    question: "What was the theme for this year's Top 10 video?",
    options: ["Rage Room", "Futuristic", "Performative Era", "Cappy Fiesta"],
    correctIndex: 0,
    durationSeconds: 20,
  },
  {
    id: "q5",
    question:
      "What is the name of the podcast filmed by Garage@EEE with NTU Entrepreneurship Society?",
    options: ["Founder's Forum", "Building Blocks", "Idea Engine", "Garage@EEE x NTU ES"],
    correctIndex: 2,
    durationSeconds: 20,
  },
  {
    id: "q6",
    question: "Who was featured in the first three episodes of the podcast?",
    options: ["Frentzen", "Mikhail", "Ken", "Raphael"],
    correctIndex: 0,
    durationSeconds: 20,
  },
  {
    id: "q7",
    question: "Which year did Garage officially start?",
    options: ["2011", "2012", "2013", "2014"],
    correctIndex: 3,
    durationSeconds: 20,
  },
  {
    id: "q8",
    question: "When did Garage officially reopen?",
    options: ["20 January", "14 January", "12 February", "25 December"],
    correctIndex: 1,
    durationSeconds: 20,
  },
  {
    id: "q9",
    question: "What was the new initiative introduced by WnO in AY25/26 Semester 2?",
    options: [
      "Hari Raya Workshop",
      "Interportfolio Bonding",
      "Garage@EEE Connect: Sports & Games",
      "Study Sessions",
    ],
    correctIndex: 2,
    durationSeconds: 20,
  },
  {
    id: "q10",
    question: "How many workshops were held by TnD this year?",
    options: ["11", "12", "13", "14"],
    correctIndex: 3,
    durationSeconds: 20,
  },
  {
    id: "q11",
    question: "How many tours has Garage hosted throughout AY25/26?",
    options: [
      "About 6 or 7",
      "11",
      "Too many, I lost track already",
      "Since when do we do Garage tours? I only know room tours by PropertyLimBrothers",
    ],
    correctIndex: 1,
    durationSeconds: 20,
  },
  {
    id: "q12",
    question: "Which of the following should members do after using Garage tools or equipment?",
    options: [
      "Leave them on the table for the next person",
      "Keep them properly and clean up the workspace",
      "Bring them home for convenience",
      "Hide them so nobody else can use them",
    ],
    correctIndex: 1,
    durationSeconds: 20,
  },
  {
    id: "q13",
    question: "How many televisions does Garage have?",
    options: ["5", "7", "8", "11"],
    correctIndex: 3,
    durationSeconds: 20,
  },
  {
    id: "q14",
    question:
      "As of 9th May 1200, what is the number of followers on the Garage@EEE Instagram?",
    options: ["2137", "67", "2582", "1849"],
    correctIndex: 0,
    durationSeconds: 20,
  },
  {
    id: "q15",
    question: "Which of the following is a flagship event that takes place in January?",
    options: ["Enitio", "IdeasJam", "Escendo", "Innovation Festival"],
    correctIndex: 2,
    durationSeconds: 20,
  },
  {
    id: "q16",
    question: "What is the name of Garage's mascot?",
    options: ["Cappy", "Leon", "Repo", "Inductorman"],
    correctIndex: 0,
    durationSeconds: 20,
  },
  {
    id: "q17",
    question: "IdeasJam is mainly related to what type of activity?",
    options: [
      "Startup ideation and pitching",
      "Ideation and prototype building",
      "Maze solving",
      "Bonding and orientation",
    ],
    correctIndex: 0,
    durationSeconds: 20,
  },
  {
    id: "q18",
    question: "How many booths do we have today?",
    options: ["9", "10", "11", "12"],
    correctIndex: 2,
    durationSeconds: 20,
  },
  {
    id: "q19",
    question: "Who do you think is the funniest person in Garage?",
    options: [
      "Bradley",
      "Stephanie",
      "Aloysius",
      "Garage where got funny people? I thought only have angry people because they GaRAGE",
    ],
    correctIndexes: [0, 1, 2, 3],
    durationSeconds: 20,
  },
  {
    id: "q20",
    question: "Who would you not let your daughter date?",
    options: [
      "Frentzen",
      "Ronald",
      "Mikhail",
      "Sasi",
      "Bradley",
      "Raphael",
    ],
    correctIndexes: [0, 1, 2, 3],
    durationSeconds: 20,
  },
];
